/**
 * Level visual themes — textures, fog, lights, props per Backrooms level.
 */
export const THEMES = {
  waterpark: {
    key: 'waterpark',
    background: 0x0b1f22,
    fog: { color: 0x1f5f63, density: 0.05 },
    ambient: { color: 0x9fe0e0, intensity: 0.55 },
    lights: {
      style: 'ceiling',
      color: 0x7fe6e6,
      intensity: 0.75,
      distanceMul: 3.6,
      spacingMul: 2,
      height: 2.85,
      flickerChance: 0.006,
    },
    ceiling: { enabled: true, type: 'tile', base: '#bcd8d6', grout: '#6fa6a6', tint: '#bfe8e4' },
    wall: {
      type: 'tile',
      base: '#dfe9e8',
      grout: '#5f8f8f',
      tint: '#bfe8e4',
      repeat: [2, 1],
      renderHeight: 3,
    },
    floor: { type: 'checker', a: '#20242b', b: '#e4e4dc', repeat: 'grid' },
    exit: { style: 'slide', locked: 0xb23a3a, unlocked: 0x3ad07a, glow: 0x8fffcf },
    props: 'slides',
    ambience: 'waves',
  },

  suburbs: {
    key: 'suburbs',
    background: 0x05070d,
    fog: { color: 0x0a1018, density: 0.07 },
    ambient: { color: 0x2a3550, intensity: 0.26 },
    lights: {
      style: 'streetlamp',
      color: 0xffb257,
      intensity: 1.0,
      distanceMul: 3.2,
      spacingMul: 2,
      height: 4.2,
      flickerChance: 0.022,
    },
    ceiling: { enabled: false },
    wall: {
      type: 'facade',
      base: '#6c6552',
      grout: '#2a2620',
      tint: '#39415a',
      repeat: [1, 1],
      renderHeight: 3.6,
    },
    floor: { type: 'asphalt', base: '#15161a', repeat: 'grid' },
    exit: { style: 'door', locked: 0xb23a3a, unlocked: 0x3ad07a, glow: 0x8fffcf },
    props: 'suburb',
    ambience: 'wind',
  },

  // Level 188 - "The Apartments": pasillos de un complejo habitacional infinito,
  // papel tapiz amarillento, alfombra manchada, fluorescentes que zumban.
  apartments: {
    key: 'apartments',
    background: 0x1a1810,
    fog: { color: 0x2a2618, density: 0.055 },
    ambient: { color: 0xc9b87a, intensity: 0.38 },
    lights: {
      style: 'ceiling',
      color: 0xe8d9a0,
      intensity: 0.85,
      distanceMul: 3.4,
      spacingMul: 2,
      height: 2.7,
      flickerChance: 0.028,
    },
    ceiling: {
      enabled: true,
      type: 'tile',
      base: '#cfc8b0',
      grout: '#8a8468',
      tint: '#d8cfa8',
    },
    wall: {
      type: 'wallpaper',
      base: '#c9b87a',
      pattern: '#b5a468',
      tint: '#a89860',
      repeat: [2, 1],
      renderHeight: 2.9,
    },
    floor: {
      type: 'carpet',
      base: '#5a4a32',
      pattern: '#4a3c28',
      repeat: 'grid',
    },
    exit: { style: 'door', locked: 0xb23a3a, unlocked: 0x3ad07a, glow: 0x8fffcf },
    props: 'apartments',
    ambience: 'hum',
  },

  // Level 2 - "Pipe Dreams": túneles de mantenimiento, óxido, vapor y luces de emergencia.
  pipes: {
    key: 'pipes',
    background: 0x0a0806,
    fog: { color: 0x1a120c, density: 0.062 },
    ambient: { color: 0x4a3020, intensity: 0.22 },
    lights: {
      style: 'ceiling',
      color: 0xff6a2a,
      intensity: 0.7,
      distanceMul: 3.0,
      spacingMul: 2.2,
      height: 2.55,
      flickerChance: 0.045,
    },
    ceiling: {
      enabled: true,
      type: 'tile',
      base: '#2a2420',
      grout: '#151210',
      tint: '#3a2a18',
    },
    wall: {
      type: 'facade',
      base: '#3a322c',
      grout: '#1a1612',
      tint: '#5a3a28',
      repeat: [1, 1],
      renderHeight: 2.85,
    },
    floor: {
      type: 'asphalt',
      base: '#12100e',
      repeat: 'grid',
    },
    exit: { style: 'door', locked: 0xb23a3a, unlocked: 0x3ad07a, glow: 0xffa060 },
    props: 'pipes',
    ambience: 'pipes',
  },
};
